name: Run-tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3.6.0
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "20.x"
          
      - run: node -v

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    
    environment: production

    steps:
      - name: use environment variable
        run: echo ${{ vars.SOME_VAR }}
      - name: use secrets
        run: echo ${{ secrets.API_KEY }}
        
